### ISSUE TITLE
Submodules are run twice per submodule when using SubModule<T>

### ISSUE THREAD

**Issue by joshslark** [thomhurst/ModularPipelines#247]
When you try to run a submodule where the action returns type `Task<T>`, it runs the action twice simultaneously. The reason is because  `SubModule<T>` inherits from `SubModule` and both constructors call `Task.Run` on the action. 

You should be able to reproduce the error by running a simple program using the `context.Command.ExecuteCommandLineTool` action as a submodule. The command will be run twice.

**Comment by joshslark** [comment]
Not positive, but I think the solution is to have `SubModule<T>` inherit from `SubModuleBase` instead of `SubModule`

**Comment by thomhurst** [comment]
Thanks @joshslark ! You're right. It's creating a Task in a constructor, and then calling its base constructor which is trying to do the same thing. I'll get this fixed. Thanks for finding it!

**Comment by thomhurst** [comment]
New version should be out that fixes this. Thanks again
