### ISSUE TITLE
webapi project support？

### ISSUE THREAD

**Issue by leehavin** [thomhurst/ModularPipelines#379]
aspnet.core project, if you call through the api, web interface display, such behaviour is supported?

**Comment by thomhurst** [comment]
@leehavin ModularPipelines doesn't require any specific system to be used. As long as the machine you're running from has the relevant permissions to do what you need, it should be fine.

**Comment by leehavin** [comment]
@thomhurst I want to develop a simple CI/CD project based on ModularPipelines for a Vue.js + .NET Core project. How can I better integrate them?

**Comment by leehavin** [comment]
@thomhurst This is a great project, but I'm struggling to figure out how to develop CI/CD using ModularPipelines for building Java and C# projects. I aim to allow users to customize project creation through the interface, followed by building and publishing.

**Comment by thomhurst** [comment]
@leehavin I can't tell you how to build your application, but you can use modular pipelines to call `dotnet` and `npm` commands like so:

```csharp
public class BuildNpmModule : Module<CommandResult>
{
    protected override async Task<CommandResult?> ExecuteAsync(IPipelineContext context, CancellationToken cancellationToken)
    {
        await context.Node().Npm.Ci(new NpmCiOptions
        {
            WorkingDirectory = context.Git().RootDirectory,
        }, cancellationToken);
        
        return await context.Node().Npm.Run(new NpmRunOptions("build")
        {
            WorkingDirectory = context.Git().RootDirectory,
        }, cancellationToken);
    }
}

[DependsOn<BuildNpmModule>]
public class DotNetBuildModule : Module<CommandResult>
{
    protected override async Task<CommandResult?> ExecuteAsync(IPipelineContext context, CancellationToken cancellationToken)
    {
        var project = context.Git().RootDirectory.FindFile(x => x.Extension == ".csproj").AssertExists();

        return await context.DotNet().Build(new DotNetBuildOptions()
        {
            ProjectSolution = project,
        }, cancellationToken);
    }
}
```
