### ISSUE TITLE
PipelineHostBuilder doesn't appear to be mentioned in the tutorial (until the 16th page!)

### ISSUE THREAD

**Issue by kelson-dev** [thomhurst/ModularPipelines#564]
The "Modular Pipelines" and "Fundamentals" sections of the docs website don't seem to say how to actually set up a ModularPipelines project with any sort of minimal example. There are code snippets for specific concepts, but nothing to show how those snippets fit into the context of an actual run-able file.

**Comment by thomhurst** [comment]
Thanks @kelson-dev ! I switched the docs framework I was using recently and it's changed the ordering of things. I've just amended so hopefully it's clearer now.

**Comment by kelson-dev** [comment]
Great, it's much clearer now! :grin:
