### ISSUE TITLE
Configuring dependencies on pipeline creation

### ISSUE THREAD

**Issue by bszymik** [thomhurst/ModularPipelines#569]
Hello, 
First of all I wanted to thank you for developing ModularPipelines it is great tool and I really like the way how it is designed, architected, and how developer-friendly it is :)

Second thing would be a question or maybe request for improvement of modules dependency configuration

Right now to configure dependency between modules it is required to use an attribute on entire class 
```
[DependsOn<ModulA>]
public class ModuleB : Module
{ ... }
```
which I think makes it a bit harder to re-use in multiple pipelines as ModuleB will always need ModuleA

Will it be possible to implement a pipeline-level configuration of dependencies?
e.g.:
```
await PipelineHostBuilder.Create()
    ...
    .ConfigureServices((context, collection) =>
    {
        collection
            .AddModule<ModuleB>()
                .DependsOn<ModuleA>()
    });

```
or something like:
```
        collection
            .AddModule<ModuleB>(typeof(ModuleA))
```

or anything that would allow to move dependency configuration from class definition?

Thanks and again I really appreciate your work!

**Comment by thomhurst** [comment]
> which I think makes it a bit harder to re-use in multiple pipelines as ModuleB will always need ModuleA

Hmm yeah I see what you mean. I guess the workaround is if you're importing a module from a library, inherit from it and add the extra attributes.

I'll have a think about this as it'd probably be quite a big refactor of dependency logic.

**Comment by thomhurst** [comment]
For now I recommend just creating re-useable library modules as abstract classes.

This will require you to then have to create a new type that inherits it, where you can place the attributes you need :smile:
