### ISSUE TITLE
context.DotNet().Tool.Update not working

### ISSUE THREAD

**Issue by bszymik** [thomhurst/ModularPipelines#582]
When calling 
```
await context.DotNet().Tool.Update(
    new DotNetToolUpdateOptions("tool_name")
    {
        WorkingDirectory = "some_path"
    },
    cancellationToken
);
```
Exception is thrown:

> System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'

Probably because it tries to parse:
```
[PositionalArgument(PlaceholderName = "<PATH>")]
public string? Path { get; set; }
```
but it is not provided, but when providing it with
`DotNetToolUpdateOptions("tool_name", path)`
but then `dotnet tool update` can not recognize that parameter

**Comment by bszymik** [comment]
Thanks!

**Comment by thomhurst** [comment]
Thanks for reporting @bszymik - can you try  version 2.40.4?
