### ISSUE TITLE
Module timeout - log standard output

### ISSUE THREAD

**Issue by bszymik** [thomhurst/ModularPipelines#632]
Hi, got another question, in case of module timeout (which default is 30 minutes) - I know that it could be changed, but if some command times-out,
is there a way to log standard output/standard error? 
e.g. we are running a module with tests:

return await context.DotNet().Test(...)

usually it takes 12 minutes but sometimes it timeouts after 30 minutes, is there a way to capture the standard output/error output when it timesout (to discover why it takes so long)?

**Comment by thomhurst** [comment]
Thanks for the report @bszymik. Can you upgrade to `2.42.45` and see if it fixes it for you? No changes should be necessary.

**Comment by bszymik** [comment]
Perfect! Works just great, thanks a lot again!
